DROP TABLE IF EXISTS movies.dbo.person;

CREATE TABLE movies.dbo.person (
  person_id tinyint NOT NULL PRIMARY KEY,
  person_name varchar(30) DEFAULT NULL,
  );
INSERT INTO movies.dbo.person (person_id, person_name) VALUES
(1,'George Lucas'),
(2,'Mark Hamill'),
(3,'Harrison Ford'),
(4,'Carrie Fisher'),
(5,'Peter Cushing'),
(6,'Anthony Daniels'),
(7,'Andrew Stanton'),
(8,'Lee Unkrich'),
(9,'Graham Walters'),
(10,'Bob Peterson'),
(11,'David Reynolds'),
(12,'Alexander Gould'),
(13,'Albert Brooks'),
(14,'Ellen DeGeneres'),
(15,'Brad Garrett'),
(16,'Allison Janney'),
(17,'Elizabeth Perkins'),
(18,'Barry Humphries'),
(19,'Bill Hunter'),
(20,'Robert Zemeckis'),
(21,'Winston Groom'),
(22,'Eric Roth'),
(23,'Wendy Finerman'),
(24,'Steve Tisch'),
(25,'Steve Starkey'),
(26,'Tom Hanks'),
(27,'Robin Wright'),
(28,'Gary Sinise'),
(29,'Mykelti Williamson'),
(30,'Sally Field'),
(31,'Don Burgess'),
(32,'Alan Silvestri'),
(33,'Arthur Schmidt'),
(34,'Sam Mendes'),
(35,'Orson Welles'),
(36,'Lars von Trier'),
(37,'Bju00f6rk'),
(38,'Sean Bean'),
(39,'Maria Bello'),
(40,'Catherine Deneuve'),
(41,'Richard Elfyn'),
(42,'David Morse'),
(43,'Peter Stormare'),
(44,'Maurice Roeves'),
(45,'Sophie Stuckey'),
(46,'Luc Besson'),
(47,'Patrice Ledoux'),
(48,'Robert Mark Kamen'),
(49,'Bruce Willis'),
(50,'Milla Jovovich'),
(51,'Gary Oldman'),
(52,'Ian Holm'),
(53,'Chris Tucker'),
(54,'Erich Pommer'),
(55,'Fritz Lang'),
(56,'Gottfried Huppertz'),
(57,'Karl Freund'),
(58,'Gu00fcnther Rittau'),
(59,'Alfred Abel'),
(60,'Gustav Fru00f6hlich'),
(61,'Brigitte Helm'),
(62,'Rudolf Klein-Rogge'),
(63,'Fritz Rasp'),
(64,'Theodor Loos'),
(65,'Erwin Biswanger'),
(66,'Heinrich George'),
(67,'Olaf Storm'),
(68,'Hanns Leo Reich'),
(69,'Johnny Depp'),
(70,'Isabel Coixet'),
(71,'Esther Garcu00eda'),
(72,'Gordon McLennan'),
(73,'Nanci Kincaid'),
(74,'Sarah Polley'),
(75,'Amanda Plummer'),
(76,'Scott Speedman'),
(77,'Leonor Watling'),
(78,'Deborah Harry'),
(79,'Mark Ruffalo'),
(80,'Jean-Claude Larrieu'),
(81,'Lisa Robison'),
(82,'Alfonso Vilallonga'),
(83,'Peter Jackson'),
(84,'Elijah Wood'),
(85,'Viggo Mortensen'),
(86,'Cate Blanchett'),
(87,'Christopher Lee'),
(88,'Orlando Bloom'),
(89,'Keira Knightley'),
(90,'Howard Shore'),
(91,'Geoffrey Rush'),
(92,'Dariusz Wolski'),
(93,'Klaus Badelt'),
(94,'Barrie M. Osborne'),
(95,'Fran Walsh'),
(96,'Philippa Boyens'),
(97,'J.R.R. Tolkien'),
(98,'Kenny Baker'),
(99,'Jake Gyllenhaal'),
(100,'Scott MacDonald'),
(101,'Peter Sarsgaard'),
(102,'Jamie Foxx'),
(103,'Bobby Cohen'),
(104,'Sam Mercer'),
(105,'Quentin Tarantino'),
(106,'Uma Thurman'),
(107,'Lucy Liu'),
(108,'David Carradine'),
(109,'William Broyles Jr.'),
(110,'Michael Madsen'),
(111,'Anthony Swofford'),
(112,'Robert Richardson'),
(113,'RZA'),
(114,'Roger Deakins'),
(115,'Jim Morrison'),
(116,'Thomas Newman'),
(117,'Walter Murch'),
(118,'Lucas Black'),
(119,'Sally Menke'),
(120,'Thea von Harbou'),
(121,'Eytan Fox'),
(122,'Gal Uchovsky'),
(123,'Hanns Zischler'),
(124,'Michael Winterbottom'),
(125,'Andrew Eaton'),
(126,'Kieran O''Brien'),
(127,'Margo Stilley'),
(128,'Marcel Zyskind'),
(129,'Katsuhiro u014ctomo'),
(130,'Clint Eastwood'),
(131,'Morgan Freeman'),
(132,'Gene Hackman'),
(133,'Richard Harris'),
(134,'Lennie Niehaus'),
(135,'David Silverman'),
(136,'Dan Castellaneta'),
(137,'Julie Kavner'),
(138,'Nancy Cartwright');

